program: train.py
method: bayes
metric:
  name: losses/recon_loss
  goal: minimize

parameters:
  lr:
    distribution: log_uniform_values
    min: 1e-5
    max: 5e-4

  l_s:
    distribution: uniform
    min: 5.0
    max: 20.0

  init_norm:
    distribution: log_uniform_values
    min: 0.001
    max: 0.05

  warmup_steps:
    distribution: int_uniform
    min: 1000
    max: 10000

  l1_coeff:
    distribution: uniform
    min: 0.2
    max: 2.0

  # Fixed parameters (you can modify these as needed)
  model:
    value: gpt2

  ae_dim:
    value: 32768

  steps:
    value: 50000

  batch_size:
    value: 2048
