[project]
name = "crosslayer-features"
version = "0.1.0"
description = "Development repo for crosslayer feature research"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "circuitsvis>=1.43.3",
    "ipykernel>=6.29.5",
    "nnsight>=0.4.8",
    "plotly>=6.2.0",
    "torch>=2.7.1",
]
