_wandb:
    value:
        cli_version: 0.21.0
        e:
            gluka6q1rhfe1ui3v4m2dv2l73elx7yr:
                codePath: crosscoder/train.py
                codePathLocal: crosscoder/train.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "62847451136"
                        used: "16682041344"
                email: rohan.kathuria@live.com
                executable: /projects/RohanKathuria/crosslayer-features/.venv/bin/python3
                git:
                    commit: 651c6e56e63cb743c2276d7858f6f368efec85c8
                    remote: https://github.com/RollingRo11/crosslayer-features.git
                gpu: NVIDIA H200
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-ee905242-1737-d644-4a30-dfa5b240cc07
                host: d4052
                memory:
                    total: "1622290128896"
                os: Linux-5.14.0-362.13.1.el9_3.x86_64-x86_64-with-glibc2.34
                program: /projects/RohanKathuria/crosslayer-features/crosscoder/train.py
                python: CPython 3.12.11
                root: /projects/RohanKathuria/crosslayer-features
                slurm:
                    cluster_name: explorer
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00000000000000080000000000000008
                    cpu_bind_list: 0x00000000000000080000000000000008
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "2"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: n.saad
                    job_cpus_per_node: "2"
                    job_end_time: "1760315567"
                    job_gid: "100"
                    job_group: users
                    job_id: "2259608"
                    job_name: bash
                    job_nodelist: d4052
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1760286767"
                    job_uid: "101226"
                    job_user: kathuria.r
                    jobid: "2259608"
                    launch_node_ipaddr: 10.99.200.107
                    localid: "0"
                    mem_per_node: "16384"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: d4052
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "41917"
                    pty_win_col: "188"
                    pty_win_row: "52"
                    script_context: prolog_task
                    srun_comm_host: 10.99.200.107
                    srun_comm_port: "38775"
                    step_gpus: "1"
                    step_id: "0"
                    step_launcher_port: "38775"
                    step_nodelist: d4052
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/kathuria.r
                    submit_host: explorer-02
                    task_pid: "1831506"
                    tasks_per_node: "1"
                    topology_addr: d4052
                    topology_addr_pattern: node
                    umask: "0022"
                startedAt: "2025-10-12T20:27:14.256940Z"
                writerId: gluka6q1rhfe1ui3v4m2dv2l73elx7yr
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
            "3":
                - 1
                - 13
                - 16
                - 61
            "4": 3.12.11
            "5": 0.21.0
            "6": 4.54.1
            "12": 0.21.0
            "13": linux-x86_64
ae_dim:
    value: 32768
batch_size:
    value: 2048
buffer_mult:
    value: 64
c:
    value: 4
device:
    value: cuda
init_norm:
    value: 0.008
l_p:
    value: 3e-06
l_s:
    value: 10
l1_coeff:
    value: 0.8
log_interval:
    value: 100
lr:
    value: 5e-05
model:
    value: gpt2
model_batch:
    value: 128
optim:
    value: AdamW
save_interval:
    value: 5000
seed:
    value: 721
steps:
    value: 50000
warmup_steps:
    value: 5000
