wandb_version: 1

ae_dim:
  value: 22819
batch_size:
  value: 1093
buffer_mult:
  value: 8
c:
  value: 5
device:
  value: cpu
init_norm:
  value: 0.10942070536107934
l_p:
  value: 2.823544620761856e-06
l_s:
  value: 19
log_interval:
  value: 60
lr:
  value: 6.825471226241108e-05
model:
  value: gpt2
model_batch:
  value: 62
optim:
  value: AdamW
save_interval:
  value: 15968
seed:
  value: 22
steps:
  value: 26896
